### PR TITLE
Better readability of binary data in the TXT record by displaying the…

### PR DESCRIPTION
**Pull request by bauerschwan**
… data as hex dump

### CODE REVIEW

**Comment by lapcat** [comment]
Thanks! Do you have screenshots of the difference? I'm not sure any of my local Bonjour records have the right data.

**Comment by bauerschwan** [comment]
> Thanks! Do you have screenshots of the difference? I'm not sure any of my local Bonjour records have the right data.

My pleasure :-) 

This is how it looked like before:
BonjeffOld

Now it looks like this:
BonjeffNew

**Comment by Kentzo** [comment]
Does this representation follow the host order or network order?

**Comment by bauerschwan** [comment]
> Does this representation follow the host order or network order?

Neither, nor. It is just a byte blob.

**Pull request merged**
